[pytest]
testpaths = api/tests web/tests
addopts = -v --tb=short
markers =
    api: Testes de API REST (Petstore)
    web: Testes E2E Web (SauceDemo)
    smoke: Testes de fumaça
    regression: Testes de regressão
