[pytest]
testpaths = api/tests web/tests
pythonpath = .
addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html

markers =
    api: Testes de API REST (Petstore)
    web: Testes E2E Web (SauceDemo)
    smoke: Subconjunto mínimo que valida o sistema está de pé
    regression: Suite completa de regressão
